name: modulx_server
description: Serveur API pour le forum ModulX
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mysql1: ^0.20.0
  dbcrypt: any
  dart_frog: any
